### ISSUE TITLE
AllenNLP version?

### ISSUE THREAD

**Issue by danlou** [nafitzgerald/nrl-qasrl#1]
I'm trying to test the predictions by following the README, but I'm having some trouble that seems related to the PyTorch version used by the master release of AllenNLP.

I'm calling the predictor with:
`python -m allennlp.run predict qasrl_parser_elmo.tar.gz examples.jl --include-package nrl --predictor qasrl_parser`

and I'm getting this error:
`AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/Users/danlou/anaconda3/lib/python3.6/site-packages/torch/_utils.py'>`

which, according to this link, seems to be related to an older version of PyTorch - https://discuss.pytorch.org/t/cant-get-attribute-rebuild-tensor-v2/15098

I've tried upgrading PyTorch to the latest version, but then other issues come up with AllenNLP. However, I've noticed that there's this branch of AllenNLP https://github.com/allenai/allennlp/tree/pytorch-0.4 .

Could you let us know if we need to use that branch, or some commit in specific?

I've read the message on the README about getting the documentation ready, if you could just share this small detail already it'd be great for those of us eager to try it out :)

**Comment by Bhaavya** [comment]
Adding the following lines of codes at the top of `site-packages/torch/serialization.py` as described here: https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560/2 worked for me.

`try:`
 `    torch._utils._rebuild_tensor_v2`
`except AttributeError:`
    `def _rebuild_tensor_v2(storage, storage_offset, size, stride, requires_grad, backward_hooks):`
        `tensor = torch._utils._rebuild_tensor(storage, storage_offset, size, stride)`
        `tensor.requires_grad = requires_grad`
        `tensor._backward_hooks = backward_hooks`
        `return tensor`
    `torch._utils._rebuild_tensor_v2 = _rebuild_tensor_v2`

**Comment by danlou** [comment]
Thanks @Bhaavya! Though, I've noticed that this is no longer an issue in the recently released version of AllenNLP (which now supports PyTorch 0.4).
